### ISSUE TITLE
I got this error,my sacred==0.7.2 same as your requirements.txt

### ISSUE THREAD

**Issue by SiriusZbz** [HyunghoNa/EMU#1]
Traceback (most recent call last):
  File "src/main.py", line 21, in <module>
    ex = Experiment("pymarl", save_git_info=False) 
TypeError: __init__() got an unexpected keyword argument 'save_git_info'

**Comment by HyunghoNa** [comment]
It seems pymarl may not be installed properly. Please check it first, referring to https://github.com/oxwhirl/pymarl.
